name: Build & Push To GH

on: [ push ]
permissions:
  actions: read
  contents: read
  packages: write

jobs:
    build_and_push_to_github:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v4

            - name: Login to ghcr.io
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build container image and push to GH
              run: |
                docker build . --tag ghcr.io/ngostal2019/flask-time:latest
                docker run -d -p 8080:5000 --name flask-app ghcr.io/ngostal2019/flask-time:latest
                docker push ghcr.io/ngostal2019/flask-time:latest
